README.md
I add your awesome bot in https://github.com/sotayamashita/awesome-css I maintain.
=> Add: README.md: used site

README.md
https://github.com/MakinGiants/awesome-mobile-dev
=> + awesome mobile dev to the list of awesome that uses this

.travis.yml, README.md
=> Travis Badge

lib/awesome_bot/links.rb, spec/parse_spec.rb
=> Handle special characters

.travis.yml, CHANGELOG.md, README.md, lib/awesome_bot/cli.rb, lib/awesome_bot/version.rb, spec/cli_spec.rb
Includes updating the CLI
Close #77, #79 
@sotayamashita care to review this ?
=> Support Multiple Files

README.md
This is related to the first checkbox in #12.
=> Added `git diff` example to README

.travis.yml, CHANGELOG.md, README.md, bin/assets/test-ssl, lib/awesome_bot/check.rb, lib/awesome_bot/cli.rb, lib/awesome_bot/result.rb, lib/awesome_bot/version.rb, spec/check_spec.rb, spec/options_spec.rb, spec/timeout_spec.rb
=> Allow SSL Errors

.travis.yml, CHANGELOG.md, bin/assets/test-invalid.md, lib/awesome_bot/cli.rb, lib/awesome_bot/version.rb
=> Invalid Byte Sequence

CHANGELOG.md, lib/awesome_bot/cli.rb, lib/awesome_bot/output.rb, lib/awesome_bot/version.rb
=> Report continued

CHANGELOG.md, README.md, lib/awesome_bot/cli.rb, lib/awesome_bot/version.rb
=> Markdown Results Table

CHANGELOG.md, README.md, bin/assets/test-dupe, lib/awesome_bot/cli.rb, lib/awesome_bot/version.rb, lib/awesome_bot/write.rb, spec/check_spec.rb
=> Cleanup markdown table

CHANGELOG.md, lib/awesome_bot/net.rb, lib/awesome_bot/version.rb, spec/status_spec.rb
=> Fix Encoding

CHANGELOG.md, bin/assets/test-errors, bin/assets/test-parse, lib/awesome_bot/net.rb, lib/awesome_bot/version.rb, spec/status_spec.rb
=> Handle incomplete redirect

.travis.yml, CHANGELOG.md, bin/assets/test-parse, lib/awesome_bot/links.rb, lib/awesome_bot/version.rb, spec/parse_spec.rb
Not super happy with this but if fixes #94
=> Fix wikipedia links with parentheses

CHANGELOG.md, lib/awesome_bot/links.rb, lib/awesome_bot/version.rb, spec/parse_spec.rb
=> Another parse regression 

.travis.yml, CHANGELOG.md, lib/awesome_bot/links.rb, lib/awesome_bot/version.rb, spec/parse_spec.rb
=> Fix wikipedia parsing issue

CHANGELOG.md, README.md, lib/awesome_bot/cli.rb, lib/awesome_bot/version.rb, lib/awesome_bot/write.rb, spec/cli_spec.rb
=> Add --skip-save-results option

.travis.yml, CHANGELOG.md, README.md, bin/assets/test-errors, lib/awesome_bot/check.rb, lib/awesome_bot/cli.rb, lib/awesome_bot/links.rb, lib/awesome_bot/version.rb, spec/parse_spec.rb
Only supports Markdown links
Close #119
=> Add --base-url option to check relative links

lib/awesome_bot/net.rb, spec/check_spec.rb
=> Use basic authentication credentials if found in the URL

.travis.yml, bin/assets/test-embedded-link, lib/awesome_bot/links.rb
=> Remove double parens, too

status/list-travis-ci, status/status.md
Add [BubuAnabelas/awesome-markdown](https://github.com/BubuAnabelas/awesome-markdown) to the status page.
=> Add awesome-markdown

Dockerfile
=> Dockerfile improvement

README.md
Reverts dkhamsing/awesome_bot#157
=> Revert "Docker instruction + examples added"

README.md
Docker instruction + examples added
=> Docker instruction + examples added

lib/awesome_bot/cli.rb
Shared some thoughts on https://github.com/dkhamsing/awesome_bot/commit/811ddf2cea614d30d9a3e80a62e7b33845d89176#r45867564
=> Delay: Integer -> Float

.github/workflows/ci.yml, README.md
=> GitHub Actions Follow ups

README.md
To use latest actions that work.
=> Update example GitHub action
